version: '3'

services:
  fluentbit:
    container_name: fluentbit
    build: ./fluentbit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - es-net
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass ${REDIS_PASSWORD}
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
        mode: "non-blocking"
        max-buffer-size: "2m"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - es-net
    
  db:
    image: postgis/postgis:13-3.2-alpine
    platform: linux/amd64
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
        mode: "non-blocking"
        max-buffer-size: "2m"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - fluentbit
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - es-net
  mongodb:
    image: mongo:6-focal
    platform: linux/amd64
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
        mode: "non-blocking"
        max-buffer-size: "2m"
    volumes:
      - mongodb_data:/data/db
      - mongo-init-db:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    depends_on:
      - fluentbit
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - es-net
  mongo-express:
    image: mongo-express:0.54.0
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
    platform: linux/amd64
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
    ports:
      - 8443:8081
    depends_on:
      - fluentbit
      - mongodb
    networks:
      - es-net
  web:
    build: .
    platform: linux/amd64
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
    command: >
      sh -c "yes | python /app/manage.py makemigrations &&
             yes | python /app/manage.py migrate &&
             python /app/manage.py runserver 0.0.0.0:8000"
    container_name: data
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_DAYS=${ACCESS_TOKEN_EXPIRE_DAYS}
      - ENCODING=${ENCODING}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - fluentbit
      - db
      - redis
      - mongodb
      - rabbitmq
    networks:
      - es-net
  adminer:
    image: adminer
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
    platform: linux/amd64
    depends_on:
      - fluentbit
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    networks:
      - es-net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
    platform: linux/amd64
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    depends_on:
      - fluentbit
    ports:
      - ${RABBITMQ_PORTS_1}:${RABBITMQ_PORTS_1}
      - ${RABBITMQ_PORTS_2}:${RABBITMQ_PORTS_2}
    networks:
      - es-net
  celery:
    build: .
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
    platform: linux/amd64
    command: celery -A core worker -l info -P threads --autoscale=10,3 -E --uid nobody
    volumes:
      - .:/app
    environment:
      - DEBUG=${CELERY_DEBUG}
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_DEFAULT_HOST}:${RABBITMQ_PORTS_1}
    depends_on:
      - fluentbit
      - web
      - rabbitmq
    networks:
      - es-net
  swagger-ui:
    image: swaggerapi/swagger-ui
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit"
    platform: linux/amd64
    container_name: swagger_ui_container
    networks:
      - es-net
    depends_on:
      - fluentbit
    ports:
      - "8181:8080"
    volumes:
      - ./OpenApi3.0.2.yml:/OpenApi3.0.2.yml
    environment:
      SWAGGER_JSON: /OpenApi3.0.2.yml

volumes:
  postgres_data:
  mongodb_data:
  mongo-init-db:

networks:
  es-net:
    name: es-net