# Generated by Django 4.0.6 on 2022-08-03 20:31

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.UUIDField(default='8893a54b-1af7-48cf-8794-6c127ab7a3c6', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_description', models.TextField(max_length=1000)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.UUIDField(default='c5b3b548-308b-4c7e-b77d-af638d35e44a', primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=1000)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('user_login_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=18, unique=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('retail_store_code', models.UUIDField(primary_key=True, serialize=False)),
                ('retail_store_name', models.CharField(max_length=1000)),
                ('retail_store_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('retail_store_city', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerUserGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_user_group_code', models.UUIDField(default='60bb2aeb-6158-4748-94e7-27c1147d4099', editable=False, primary_key=True, serialize=False)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('user_access_level', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_input_code', models.UUIDField(default='78ecffef-43e8-4b15-a4a9-0b88256c05ff', primary_key=True, serialize=False)),
                ('customer_code', models.UUIDField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('customer_csv_uploaded_name', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_input_description', models.CharField(max_length=500)),
                ('csv_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('csv_name', models.CharField(blank=True, max_length=500, null=True)),
                ('csv_number', models.IntegerField(default=1)),
                ('csv_hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('gridfs_code', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.retailstore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.user'),
        ),
    ]
