# Generated by Django 4.0.2 on 2022-03-18 19:01

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.UUIDField(default='13cc8a38-3a2a-4d29-9d0f-09f766c076ba', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_description', models.TextField(max_length=1000)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_input_code', models.UUIDField(default='4ce49d16-edfa-4366-8412-59b73ec90d01', primary_key=True, serialize=False)),
                ('customer_code', models.UUIDField(blank=True, null=True)),
                ('customer_input_name', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('customer_csv_uploaded_name', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_input_description', models.CharField(max_length=500)),
                ('csv_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('csv_name', models.CharField(blank=True, max_length=500, null=True)),
                ('csv_number', models.IntegerField(default=1)),
                ('csv_hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('gridfs_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.UUIDField(default='bec56b86-439f-41e9-907c-06516790ac74', primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=1000)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('user_login_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=18, unique=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('retail_store_code', models.UUIDField(primary_key=True, serialize=False)),
                ('retail_store_name', models.CharField(max_length=1000)),
                ('retail_store_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('retail_store_city', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerUserGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_user_group_code', models.UUIDField(default='2c42d50b-2e5e-4d67-b170-2d215240319f', editable=False, primary_key=True, serialize=False)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('user_access_level', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
    ]
