# Generated by Django 4.0.2 on 2022-03-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f045174c-8b70-4a27-aac6-22c6a51c7367', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='80e8d696-6873-4183-97af-425c9e77ca52', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='ab377fe9-950b-4550-adbe-2238552d1304', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='97f88f9a-5bb0-44f3-b9ff-afe9168afea8', primary_key=True, serialize=False),
        ),
    ]
