# Generated by Django 4.0.1 on 2022-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_product_rename_userlogin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('product_input_code', models.UUIDField(default='229eb7d7-3f6a-4e6a-afcd-f0f5b6b9d5d8', primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('product_input_description', models.CharField(max_length=500)),
                ('cvs_location', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='70622a90-0e65-499b-9ca4-0382465ad8d0', primary_key=True, serialize=False),
        ),
    ]
