# Generated by Django 4.0.6 on 2022-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='00f71aaf-504c-44ba-b3c3-11bc15aa69cf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='cbf125be-54c8-4586-8da4-44957dd2e5f6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='d204fe49-35a2-4df4-833b-0ca4d40bd904', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e5d34d41-ac34-421a-a366-d030c9f0c588', primary_key=True, serialize=False),
        ),
    ]
