# Generated by Django 4.0.1 on 2022-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_productinput_alter_product_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.UUIDField(default='dbd3c566-2607-4079-baf0-1d4ad89f58bb', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_description', models.TextField(max_length=1000)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='fc28adc4-58fe-4bee-9ba9-fab386f336a6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinput',
            name='product_input_code',
            field=models.UUIDField(default='0963d25b-c787-4894-8e7c-210d5f703e04', primary_key=True, serialize=False),
        ),
    ]
