# Generated by Django 4.0.2 on 2022-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6b6d2fb3-2d83-4ab0-b047-27e9dadde220', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='e9007435-5af6-4b2f-9016-51798d4fb14a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='386b9ab5-0208-4262-b955-92b038089fc6', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='29a649ec-3512-478c-ab1e-a020c5f89182', primary_key=True, serialize=False),
        ),
    ]
