# Generated by Django 4.0.1 on 2022-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_customer_alter_product_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5de1c01d-7a65-452d-a921-28acfd5efbe9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0ed0bab9-85d4-48d0-a74f-cba2d54088a5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinput',
            name='product_input_code',
            field=models.UUIDField(default='81cdf20c-64f5-4902-a6b6-2bdddb498e46', primary_key=True, serialize=False),
        ),
    ]
