# Generated by Django 4.0.2 on 2022-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='92cbf0c7-6265-4514-986d-93e212453b0a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='37c76636-a8bd-4c45-abee-f3bd01b83c75', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='79e12c7b-7e1a-4247-b0a8-e87fd57e02f8', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1e2daa7d-7f77-4504-8a4d-f632f7334530', primary_key=True, serialize=False),
        ),
    ]
