# Generated by Django 4.0.1 on 2022-02-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='bd410d30-8ff1-4759-9fe7-29de5b980963', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f0dd3749-e83f-4c34-9fb7-64a66ed104ea', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinput',
            name='product_input_code',
            field=models.UUIDField(default='3226b9f1-eb6e-43f5-9985-9763c0522528', primary_key=True, serialize=False),
        ),
    ]
