# Generated by Django 4.0.2 on 2022-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5f5eafdd-d904-4f8f-b8b7-27311f44e93b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='5e5b2a20-2586-4744-9f8a-0239e538b8d9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='13cd67b7-0152-4479-abf3-17bcadbb73db', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='b87dac87-da11-4467-ba91-b3745428a421', primary_key=True, serialize=False),
        ),
    ]
