# Generated by Django 4.0.2 on 2022-03-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinput',
            name='retail_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.retailstore'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='fe4b58bf-a8a6-494a-a3a3-4addf5ace75e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1c76db2e-205e-48b3-b584-6ade5124690e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='b4e6c43f-f3c1-4f6b-ab12-ca4e8346ed62', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='62f108cb-a822-4d58-b34b-50f5f8d3a09d', primary_key=True, serialize=False),
        ),
    ]
