# Generated by Django 4.0.1 on 2022-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='08e0098d-d7c4-4aae-92a8-6edf1e1ae054', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f97d37a1-0c08-4f13-a23e-e55021363418', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinput',
            name='product_input_code',
            field=models.UUIDField(default='f74de8c6-4cd4-4059-87b0-d4f642b9a974', primary_key=True, serialize=False),
        ),
    ]
