# Generated by Django 4.0.6 on 2022-08-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4e6956e0-9eff-463a-87b8-bc63db2f111b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='11c7b776-61bb-4cc9-ae0e-3f66ff32ca8c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='b13de35b-0ef2-4cc0-8039-8944e2375c45', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='80aa1f05-7c43-4d6f-a05d-dc67708660f4', primary_key=True, serialize=False),
        ),
    ]
