# Generated by Django 4.0.1 on 2022-02-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c90e188b-0b7b-4438-a215-814b40c50aa4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c0b8a3d1-7ab3-4431-91b6-035469ff288a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinput',
            name='product_input_code',
            field=models.UUIDField(default='8244c4ba-3371-402b-8808-14d1431e0257', primary_key=True, serialize=False),
        ),
    ]
