# Generated by Django 4.0.6 on 2022-08-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='0e50b5f2-d62e-44f5-91cf-2f3da9c42df3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f6719d4b-aae5-451d-8ac5-77961e75a230', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='01b1ca70-3ca9-46d7-bc6a-472588e42d2a', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c048a905-9db1-46aa-a56c-e3633440ebbf', primary_key=True, serialize=False),
        ),
    ]
