# Generated by Django 4.0.6 on 2022-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='cdce552f-d42d-43ec-bff7-fb4c7763ec7e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7bea3030-83ee-46be-981d-2dbcac38a0c5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='f90462b9-80ea-4e57-bc3f-6e6390c6528a', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='174517b6-ccd0-4554-996f-b38306c0e4b3', primary_key=True, serialize=False),
        ),
    ]
