# Generated by Django 4.0.1 on 2022-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_customerinput_delete_productinput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f228f1fb-a4bd-43ec-a7bf-8ec2b6f81a5f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='25e971f5-fcae-42c5-855c-d93f9fc7c6d5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='aa03250c-7b42-4848-a3fe-a780283d6f39', primary_key=True, serialize=False),
        ),
    ]
