# Generated by Django 4.0.6 on 2022-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='7e89880f-ca13-4299-933f-f6a0457ffd76', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d346bbb9-fbaa-40ae-ae6c-6170eba7bd2a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='093ad966-0c05-4f2a-bd58-39f64502f3c9', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8e325e89-4b58-40cd-a180-723b389d1ba8', primary_key=True, serialize=False),
        ),
    ]
