# Generated by Django 4.0.2 on 2022-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a8ea0f00-3480-4d7c-8ea5-66a1d5d1ac72', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='37518b06-f75f-4fbb-99ce-a6ae1166ca5c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='32f4fcd9-a33b-4539-bddd-78914256e335', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='48b6ab15-99f5-4aab-b09a-266fbe9cf3aa', primary_key=True, serialize=False),
        ),
    ]
