# Generated by Django 4.0.6 on 2022-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e32ef7bf-7c2a-453a-80fe-e0395fe9ff9d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c79812da-b589-423b-ab5a-7f392707b38d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='b27925cf-c97f-4f7e-96f6-6d568abd539a', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6b4be71c-4e14-4687-b8b8-e621a0b48d9c', primary_key=True, serialize=False),
        ),
    ]
