# Generated by Django 4.0.1 on 2022-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='88bf8562-f059-429c-8c2f-572e32f5d550', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='327f9e58-ef52-4a5e-b51a-8034e7b2a7e0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a88258b0-b5f1-4efa-bb11-2165d32e9436', primary_key=True, serialize=False),
        ),
    ]
