# Generated by Django 4.0.2 on 2022-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='98e6128b-158c-4660-9b27-008251da4afe', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='9a3f3350-3440-4f79-9fe4-78efe2f95741', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='aa1a67b3-f081-4fc1-a13c-7e37b189f072', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8eb01132-1a63-4349-b808-0f4a5cfb38c9', primary_key=True, serialize=False),
        ),
    ]
