# Generated by Django 4.0.2 on 2022-03-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='54d5f444-de2b-44c2-8004-43080f055f21', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='cfa2bfde-6a04-4181-b46c-e5beaaa15e17', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='4a452ee0-1fac-4a94-8805-a353348eedd7', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8d925ded-447f-499d-80ed-ed790f3c9015', primary_key=True, serialize=False),
        ),
    ]
