# Generated by Django 4.0.6 on 2022-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='582a8677-e0b6-4e97-aa2b-23631281a40b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='0b822ea9-eb64-463f-8101-c39bdef9b7db', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='1d0af326-267b-4ca1-bd58-972f9ea41447', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='3c0b8519-c917-49b1-8f15-a65d5583e766', primary_key=True, serialize=False),
        ),
    ]
