# Generated by Django 4.0.1 on 2022-02-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='49ae9d7b-8298-4cef-a457-419ca960e2cb', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6693fac6-4598-45d5-896e-a091302655d8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='4e27c75e-b7d2-44f1-9357-90ed53afcd08', primary_key=True, serialize=False),
        ),
    ]
