# Generated by Django 4.0.2 on 2022-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5eb78a7c-eb40-4b28-af82-918ec025a248', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6e2c93f6-b935-413a-8983-85d916e53c75', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='99ad68cc-0447-439b-90f8-d559240bd25a', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f5afb9ea-7fd1-472a-8df0-9dc0c6d5175c', primary_key=True, serialize=False),
        ),
    ]
