# Generated by Django 4.0.1 on 2022-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4171cb48-d0c0-45ac-b1fd-aeab95bfb200', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='8d639d50-d219-408c-93bd-2ede11437323', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d0032545-2068-420b-84ea-2e35c8e84aad', primary_key=True, serialize=False),
        ),
    ]
