# Generated by Django 4.0.2 on 2022-03-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='7ff3a555-85f2-4b61-afc4-c400f50fd0e3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7340b97a-f440-4196-b000-b4d198c74146', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='7b3d2dfa-ca20-4cdc-8d19-76c200bdba88', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d18291ce-f6d0-4137-b6a5-208c9e93d757', primary_key=True, serialize=False),
        ),
    ]
