# Generated by Django 4.0.2 on 2022-03-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinput',
            name='customer_input_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5a0a1e7e-4578-4d77-a3d3-5821e211c5b1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='5a7707d9-fdb2-4501-84c8-a26cf6826750', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='3da5ec9f-4f2b-46f2-8355-1d0844a7320b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='9145cd8b-20e8-4b2d-af5d-99c08911065d', primary_key=True, serialize=False),
        ),
    ]
