# Generated by Django 4.0.1 on 2022-02-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d7b25cce-53c2-4eb1-b604-5b3413972ef6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='008d00b7-19b2-4c61-ac15-0529e59a7dc2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='84ded56e-8fd8-43e2-bea9-c04c82bb2428', primary_key=True, serialize=False),
        ),
    ]
