# Generated by Django 4.0.6 on 2022-09-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='46ea1092-dcf7-46d0-8fc6-f1c19b07a606', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='b4f466f6-c698-40bf-9e63-0c973b7ba0c7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='852300f2-a256-46aa-95fc-8772c02cb13d', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='22d0c54b-44d0-4b4d-b7ef-b1137f4d84c0', primary_key=True, serialize=False),
        ),
    ]
