# Generated by Django 4.0.1 on 2022-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6b7cf8e4-1899-40c5-95d7-97d346c3eec2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='e738d4cc-d175-47ad-9096-c6594d3df4cb', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='399e44f7-cb65-41a6-b280-097e49053520', primary_key=True, serialize=False),
        ),
    ]
