# Generated by Django 4.0.2 on 2022-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_customerinput_customer_input_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='8db0393c-4af1-4734-981f-bd54742a0680', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='b660b0d4-7b9e-4842-9fcb-6b6fb6390b0c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='c6b3c8f6-1dc1-4ecb-8eba-ac88b948cef9', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7912d0f1-422a-4efd-81d5-2ca8aaa21b1e', primary_key=True, serialize=False),
        ),
    ]
