# Generated by Django 4.0.6 on 2022-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='168e2e84-d4a3-4fd6-a006-18afceb56c33', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1dff72c4-cd78-4b90-b5c6-2d7bf88edae6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='69eaad97-fe5a-44cf-99b3-5dc02480dfd5', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0b5b63de-0e2b-44b7-ab15-a9c65185f9b4', primary_key=True, serialize=False),
        ),
    ]
