# Generated by Django 4.0.1 on 2022-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='ecf9f7b6-7896-4b3a-83d8-726093e1c487', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='99e803fc-2201-43e0-bcfd-f48f458e479a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0cfd542a-c659-45d1-8c2a-b0e838a78483', primary_key=True, serialize=False),
        ),
    ]
