# Generated by Django 4.0.2 on 2022-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='02317e4e-ef78-4644-a381-20dee8b32b1d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c8c393cf-2ad2-4f7a-9061-d23c94b13384', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='958f27ba-3b51-4b49-adfc-fdba21b9e07e', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e53d46c1-6d00-46ea-9505-6aed59fc13ee', primary_key=True, serialize=False),
        ),
    ]
