# Generated by Django 4.0.2 on 2022-03-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4bf8ab3e-ea19-4b09-a77f-d26a28233ead', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='2f39c1e6-0561-49c2-abf9-650dc9ce85f0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='f85cd0e4-0e1e-4433-a352-6f42c818cfca', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f4cb7ef4-9292-42de-9101-4510fa6970ea', primary_key=True, serialize=False),
        ),
    ]
