# Generated by Django 4.0.1 on 2022-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='805fed9d-71a0-4dd5-800c-c0bebdf7dfd2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='5ca269c1-f44f-4557-80d6-aac65d8570f4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='b522efe7-7fcc-4305-821c-0664e0921b12', primary_key=True, serialize=False),
        ),
    ]
