# Generated by Django 4.0.1 on 2022-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='7c3c45aa-f5ac-488e-8e6f-62cad9198a91', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='a69d0eea-6414-48ec-ae9a-1efc7ca005e4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d96a7d6b-806f-4359-b4e1-f219e8bca457', primary_key=True, serialize=False),
        ),
    ]
