# Generated by Django 4.0.7 on 2022-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='31b3656f-cff4-4d6f-b2ae-d97da19d4ad7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='387a50f6-cb2b-46c1-9a33-2e81d097a813', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='8700367e-0816-4802-9c5c-511fce2c3c9a', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e1eecf2a-3436-4f72-aaea-0b9c977ae893', primary_key=True, serialize=False),
        ),
    ]
