# Generated by Django 4.0.2 on 2022-04-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='37d7a463-fec2-4854-9f0e-9a8f29ae66e4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ecba4ed8-d0f8-4273-89e0-c8232dcaee33', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='4f24d374-d317-4abd-b541-cd04d3e6b27b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e2feb377-5882-4dda-8638-d16e6a2d8d1a', primary_key=True, serialize=False),
        ),
    ]
