# Generated by Django 4.0.1 on 2022-02-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='819a2fc8-6eb6-4b30-8087-3c0be0163470', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='8399f3bd-1bea-4c83-b4b8-5463589497a4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='74097262-590a-495c-938d-11ee7cc62361', primary_key=True, serialize=False),
        ),
    ]
