# Generated by Django 4.0.2 on 2022-04-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2278afd6-049b-4c7a-9073-f5df7470aa2e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='fb886bb1-d263-423f-a1a2-56373f92c62c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='5c17efbe-ce77-477e-aef2-a6402f847570', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='710268c1-266f-45cc-b9f2-f16da824bdf9', primary_key=True, serialize=False),
        ),
    ]
