# Generated by Django 4.0.7 on 2022-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='250b492c-4d97-483d-b7e5-965ab5ea46ca', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='58a482ba-4bed-43ae-aaff-4adf112f8980', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='2344d20e-a9fe-46f3-9a5a-73890e689a14', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='86bb38e6-c814-4bae-ad30-335f3d7ab48e', primary_key=True, serialize=False),
        ),
    ]
