# Generated by Django 4.0.7 on 2022-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4c294bd9-52dd-4c7b-8d19-5205b2b8e09e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='e07a92ee-1c4f-4743-bfcd-76013b4f3a5a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='a49c5278-2952-4d42-848e-36bf97b6f798', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a5b9cd58-86cc-4b0a-aa40-451209d9abe7', primary_key=True, serialize=False),
        ),
    ]
