# Generated by Django 4.0.2 on 2022-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='43cf6c0e-36a9-4310-9d0c-63b3259253f1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d1e277f3-52d4-413b-a494-908e16514ebc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='9e0871f6-8408-49c2-99f6-7d08b95754d3', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='ca7059da-ea4f-4594-a0f3-244c94500105', primary_key=True, serialize=False),
        ),
    ]
