# Generated by Django 4.0.1 on 2022-02-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a90b60ff-911d-45c8-a00a-8cec4e21b987', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d20a3225-3fe4-4fb2-98d8-df758df0755d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7148e4ba-e790-4255-ae06-da683e9b087e', primary_key=True, serialize=False),
        ),
    ]
