# Generated by Django 4.0.7 on 2022-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2650ce2e-b83b-4044-a29d-4c37041db475', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6ce545f2-f7b4-4471-b5d5-8280b93d3914', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='40ce46d1-91da-48b8-9df5-d2a05d18d387', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d5533a5f-8abf-4afb-a804-c93b4ef9b8cd', primary_key=True, serialize=False),
        ),
    ]
