# Generated by Django 4.0.1 on 2022-02-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6584f9f8-d5e4-43d4-a288-af28cce7e3e2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ee561212-4e38-4f17-90e0-9a2db5d02c69', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c4c7ab55-6844-4332-b6ba-941c5e5adfb2', primary_key=True, serialize=False),
        ),
    ]
