# Generated by Django 4.0.2 on 2022-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a403b4bb-0e4c-42d2-9584-e9a4894b1bde', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d8df54d4-b1de-4d8b-8f8d-c5c05ee01b5c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='4d1e723c-7913-4337-b79c-f16cbd8ea2f4', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='be07dddb-f349-49ee-9753-780f6ead6cb2', primary_key=True, serialize=False),
        ),
    ]
