# Generated by Django 4.0.2 on 2022-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='019f33da-d2a3-4fff-a8b4-c9a6d80514f8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='65f9ce8f-2e6a-484f-9b75-93723905d0ce', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='eb84e0a6-9eb2-47ec-b463-ad6d99647275', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c4b6e212-2317-4894-821b-8c99ea329593', primary_key=True, serialize=False),
        ),
    ]
