# Generated by Django 4.0.1 on 2022-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='91a923d5-103f-41f9-bcb2-f991d08c13fa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ca167456-cf1e-4e50-a25c-eac86f518270', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='715c8de8-7399-4243-88b7-95364237c04f', primary_key=True, serialize=False),
        ),
    ]
