# Generated by Django 4.0.7 on 2022-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='ca877bb1-9ffe-4bb4-b34c-82e23b040981', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f2b8fcc0-f6f9-4331-9368-d5a8412e9dbf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='6bfb8d95-5c4b-43ed-b1c3-96adc27246f5', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1fd2c8f4-a479-4595-94b0-e8cd571039a8', primary_key=True, serialize=False),
        ),
    ]
