# Generated by Django 4.0.2 on 2022-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='47d8c556-ba69-44e0-8122-afc0c6f4bd56', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='02d1c923-2095-4bc9-a490-6fb3ac1716f1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='edeb3495-f934-4244-9f10-eaf54057f0c0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7df71e92-f8f4-4668-acad-03513ec82c81', primary_key=True, serialize=False),
        ),
    ]
