# Generated by Django 4.0.1 on 2022-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinput',
            name='cvs_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customerinput',
            name='cvs_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customerinput',
            name='cvs_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e86c7d39-677b-413d-954a-92e5db1056bd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='0387f838-597f-422e-acbf-bb166b1b19df', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='51cc1e9f-58a8-4142-89f1-021ca2a45e56', primary_key=True, serialize=False),
        ),
    ]
