# Generated by Django 4.0.7 on 2022-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='10ab7e97-d9bd-4503-8744-e17130d52419', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='b2090b7c-2c82-490a-9064-6f98622609de', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='d4191b4c-286a-41b9-b63d-ebb5c64f0c28', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a7cd2014-9e11-44b3-9d0b-879c957e83f4', primary_key=True, serialize=False),
        ),
    ]
