# Generated by Django 4.0.1 on 2022-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_customerinput_cvs_hash_customerinput_cvs_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinput',
            name='customer_code',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c4c60f22-878a-4cba-b96f-9ff86c6ff8cb', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='b0b119b2-7e12-4c4d-99e2-51feb12565fa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='84c74e29-b477-4c89-9aa3-0c92bde7e43e', primary_key=True, serialize=False),
        ),
    ]
