# Generated by Django 4.0.2 on 2022-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b4674717-7a8f-46c3-978f-5cc6e93bb59a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='13f4e3ea-012c-47f1-a1db-f264df7cbe43', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='e57fcbb4-248c-43c5-a416-4f54ffc99164', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='5b766e93-c139-4163-b544-9cf527eb1c18', primary_key=True, serialize=False),
        ),
    ]
