# Generated by Django 4.2 on 2026-07-13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0025_alter_customer_customer_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_code",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customerinput",
            name="customer_input_code",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customerusergroup",
            name="customer_user_group_code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
