# Generated by Django 4.0.2 on 2022-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='307cb0d8-74c6-4cda-a39a-c806cf6e8cb9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7c0153f7-ec90-4f59-a8cc-0ba058a6b58b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='4f0d7173-fbc3-489b-b951-10bf59e64597', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='355c6e87-3aed-4515-855a-73038ac93dc5', primary_key=True, serialize=False),
        ),
    ]
