# Generated by Django 4.0.1 on 2022-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_customerinput_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='bed3e526-914c-44c2-85f9-0cdf5247597a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='30493e14-9340-42d7-9271-545abb3a35d8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d5a43bb4-2402-4224-8e36-e0b9ad981e3b', primary_key=True, serialize=False),
        ),
    ]
