# Generated by Django 4.0.2 on 2022-05-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4d68b4a2-76a3-4a85-99dc-171b068c4480', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='20f10bc6-ac24-427e-8062-f7ea929e9dce', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='f7ca86fb-5879-4d63-a797-3c2eb7df96c9', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='699833c7-302c-47b6-be55-86d2cc5ef268', primary_key=True, serialize=False),
        ),
    ]
