# Generated by Django 4.0.2 on 2022-04-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c034c7b8-f21d-497a-b36a-6292a7cd946a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ac0ceae7-8fce-47d9-b4bf-af37b1ef3d56', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='4e0f87dd-8c6c-416f-a12a-fec503621891', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='cb780145-b739-498c-bed3-8bcf9767ef16', primary_key=True, serialize=False),
        ),
    ]
