# Generated by Django 4.0.1 on 2022-02-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4b72d344-f740-4ed0-989c-c614fbcb8c36', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='42df8719-6547-41b3-a338-27f62245a64a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='499c2e37-7553-4fd2-b809-eee4e7e8c62d', primary_key=True, serialize=False),
        ),
    ]
