<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-05-17 18:22
=======
# Generated by Django 4.0.2 on 2022-04-29 13:38
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='787fbfbb-04e5-4e2b-963f-0d11d500b322', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='f1c17a76-9eba-41e5-925a-591893cc9f58', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='97be0f83-7b83-4016-8ca2-4215d6fe145d', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='a156ad8a-de95-4863-8fca-4b92e692e40e', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='e86b5816-dd6c-4ddb-bc84-5b044a359b46', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='dcb5b418-d7f8-43b1-aeec-6360646ad077', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='ba1437ef-10a7-4d30-b803-a8e8c1a86562', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='874c1f91-04ec-408a-ba86-a475b93683ec', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
