# Generated by Django 4.0.2 on 2022-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d0c2b525-ba7f-41e5-87e4-02f2be6a1a53', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c97aee07-af11-4045-a7a2-67de2d29b1b9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='733527d5-129a-4ac5-8890-751faaa2d782', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='ac87da2f-9a59-42cf-9827-92796fbb2bef', primary_key=True, serialize=False),
        ),
    ]
