<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-05-18 17:21
=======
# Generated by Django 4.0.2 on 2022-04-29 15:05
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='c1bb2885-234f-4ed6-8ce8-d620498d7700', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='d0c2b525-ba7f-41e5-87e4-02f2be6a1a53', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='16f32e56-3155-4f0b-a2c7-3699bd38c410', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='c97aee07-af11-4045-a7a2-67de2d29b1b9', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='08387191-f338-4ff3-af57-ec9331fdeea0', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='733527d5-129a-4ac5-8890-751faaa2d782', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='061bed5e-5783-4612-928a-f4d90c7f9025', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='ac87da2f-9a59-42cf-9827-92796fbb2bef', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
