# Generated by Django 4.0.2 on 2022-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c1bb2885-234f-4ed6-8ce8-d620498d7700', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='16f32e56-3155-4f0b-a2c7-3699bd38c410', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='08387191-f338-4ff3-af57-ec9331fdeea0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='061bed5e-5783-4612-928a-f4d90c7f9025', primary_key=True, serialize=False),
        ),
    ]
