<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-05-31 17:49
=======
# Generated by Django 4.0.2 on 2022-04-29 15:21
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='653ac084-f0e5-4b59-a956-d4437b03f223', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='f3972f61-7843-4958-a191-2d83668e1516', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='835e4c4a-47f4-49b3-8ff9-f241ee6d003e', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='539008d4-afa1-4a21-b25b-b243a0a0aeba', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='739f7956-3cde-47aa-a6a6-806f7bd07c25', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='42ea4e0b-5fc3-430e-8ed4-12a45ffbb6f4', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='a4f5b52d-43ca-415b-9f33-bcd13e915d2f', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='f066aaaa-49a5-4dd8-a9e5-49f7011ea668', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
