# Generated by Django 4.0.2 on 2022-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f3972f61-7843-4958-a191-2d83668e1516', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='539008d4-afa1-4a21-b25b-b243a0a0aeba', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='42ea4e0b-5fc3-430e-8ed4-12a45ffbb6f4', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f066aaaa-49a5-4dd8-a9e5-49f7011ea668', primary_key=True, serialize=False),
        ),
    ]
