# Generated by Django 4.0.1 on 2022-02-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f580d934-6d3a-4961-bdef-6f3c577b42d7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f190b9d3-c4e9-476f-812a-34e97616339a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6488dd84-8fe1-4b57-925f-78cb5875f370', primary_key=True, serialize=False),
        ),
    ]
