# Generated by Django 4.0.2 on 2022-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='70902536-7894-454f-bac7-fd8c94617013', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6241c29f-f2d4-41b8-a690-b153201b414f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='52cab0fc-a7cb-4ecf-aacf-bbe0aba7d5c4', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d63f21a7-60f3-4d1c-a077-d196bc2a26dc', primary_key=True, serialize=False),
        ),
    ]
