<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-05-31 17:53
=======
# Generated by Django 4.0.2 on 2022-04-29 17:45
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='5cda703c-9093-4e73-89ad-2967b43fd088', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='70902536-7894-454f-bac7-fd8c94617013', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='5de01455-ac55-417b-a836-6ecea9dcfb7b', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='6241c29f-f2d4-41b8-a690-b153201b414f', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='2c5f7f2e-9d7d-4fba-85db-b092919ca040', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='52cab0fc-a7cb-4ecf-aacf-bbe0aba7d5c4', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='cee579e0-7129-4881-9b3b-3e4630eb0f75', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='d63f21a7-60f3-4d1c-a077-d196bc2a26dc', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
