# Generated by Django 4.0.1 on 2022-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinput',
            old_name='cvs_hash',
            new_name='csv_hash',
        ),
        migrations.RenameField(
            model_name='customerinput',
            old_name='cvs_location',
            new_name='csv_location',
        ),
        migrations.RenameField(
            model_name='customerinput',
            old_name='cvs_name',
            new_name='csv_name',
        ),
        migrations.RenameField(
            model_name='customerinput',
            old_name='cvs_number',
            new_name='csv_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='54dfcb97-a873-4854-9556-9fad773ee7df', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='320eaf08-3048-4b78-b026-d17fde17a864', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6e8466c4-481a-4bee-805e-ea6b05124faf', primary_key=True, serialize=False),
        ),
    ]
