# Generated by Django 4.0.2 on 2022-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e6804161-a142-4ddc-bbef-93c0aa30ea60', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d00874c1-3f61-4bda-b4e9-127c1e6f13cd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='dad0ba11-7033-4034-b7cc-5b933bc35be5', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f19d8d59-238d-4cb2-8d45-09ca27ef997a', primary_key=True, serialize=False),
        ),
    ]
