# Generated by Django 4.0.2 on 2022-04-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c56e572b-6c63-48f8-95d4-d022ac516783', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='cdac4b9e-234d-4f92-91bf-da3c2fffacc0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='5c42819a-032e-4f11-906d-0eab3c0727a0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='74655540-5c5b-46f6-a234-6acffb8fe008', primary_key=True, serialize=False),
        ),
    ]
