# Generated by Django 4.0.1 on 2022-02-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='bb7b4788-33b6-4fc3-868c-e4af18d1fa86', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='csv_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='50d60d58-cd09-4a05-a0da-fa443bcb5047', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='52302bb2-fac1-4553-b20c-53686dd2d9d0', primary_key=True, serialize=False),
        ),
    ]
