# Generated by Django 4.0.2 on 2022-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='8dcf0e26-b5a1-4720-96ea-7c533e67bba4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='8d8e5f01-d930-41af-837c-93a09022e9c8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='29be0bd0-a634-4d72-ae50-04d0404eddc7', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a3da12d8-759d-494c-890a-cfa2b2d8a10b', primary_key=True, serialize=False),
        ),
    ]
