<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-06-02 17:37
=======
# Generated by Django 4.0.2 on 2022-04-29 18:25
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='8dcf0e26-b5a1-4720-96ea-7c533e67bba4', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='8d8ea0c3-e241-436c-be91-da57d48ffa63', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='8d8e5f01-d930-41af-837c-93a09022e9c8', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='ceedcc11-1e02-4ed8-aaac-cbd5ab52ffcd', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='29be0bd0-a634-4d72-ae50-04d0404eddc7', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='3940a7ad-7b01-457e-8301-56dd2d7d0d64', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='a3da12d8-759d-494c-890a-cfa2b2d8a10b', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='da53f9fe-3795-4698-95c5-10724608a423', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
