# Generated by Django 4.0.2 on 2022-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d1d6b821-093a-4990-887e-9939594bc7c7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='665728d9-3c05-4142-80ed-d99251145c7e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='4593f497-5792-473b-aff7-cba8d5f09b0e', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='bb2b8672-e02e-4e3e-8269-f00541e5d385', primary_key=True, serialize=False),
        ),
    ]
