# Generated by Django 4.0.2 on 2022-06-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='0f5167a6-bbba-4343-94ff-59913c856c0a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1779b54b-72e0-4221-b3d8-8c73ad31d415', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='fe0cb23e-c4b3-4b66-812f-e014bdc9b0ad', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='21500a46-9c68-4325-b129-ba6d2b59a002', primary_key=True, serialize=False),
        ),
    ]
