<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-11 12:42
=======
# Generated by Django 4.0.2 on 2022-06-06 19:03
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='bdb83b5d-1ae7-4c5e-b417-9b2e7d5efdeb', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='5fb59eb9-3a51-47fd-8fd1-e42740120865', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='90951527-f606-4f3d-8ca4-17e21ae19743', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='3c8fda4c-590f-4094-8e83-c7c48afe90ef', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='360b109e-8539-457f-92db-53b7c5d617be', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='211949c8-5a2c-42d2-85e4-0c5b45177dc4', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='1febb8ad-34af-4e3d-b838-b76d1091601c', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='7a67a60f-dd78-4d1c-aa3e-0a0f804a8459', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
