# Generated by Django 4.0.1 on 2022-02-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='9ad6c0b0-f922-43a9-ac06-f6fbfaaef582', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='97734627-36d1-435d-898c-9b6698df52f9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='4a06e575-4893-43a3-af45-22820c79b9c0', primary_key=True, serialize=False),
        ),
    ]
