# Generated by Django 4.0.2 on 2022-07-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='bdb83b5d-1ae7-4c5e-b417-9b2e7d5efdeb', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='90951527-f606-4f3d-8ca4-17e21ae19743', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='360b109e-8539-457f-92db-53b7c5d617be', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1febb8ad-34af-4e3d-b838-b76d1091601c', primary_key=True, serialize=False),
        ),
    ]
