<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-11 22:49
=======
# Generated by Django 4.0.2 on 2022-06-06 19:06
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='07ddbf52-893a-4eb6-82e0-593e33ce9ae4', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='371fb5fa-6c11-4748-b8ea-0aea4f052a77', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='3ce2c918-27b8-422c-ae95-24777e980154', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='0c6e5351-001a-4b64-989a-2969dc6dcfff', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='78236651-66f8-458e-9939-f4c93aff38e8', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='a456d2e1-3181-4abf-95c3-6362ced36c2d', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='b025d289-4041-4702-8874-2b9f605800a5', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='367161c6-a6ed-47f6-8b42-257708cafb53', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
