# Generated by Django 4.0.1 on 2022-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='89f3bb81-d630-4a33-9c7c-15cfe6575969', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3268fd64-0753-496a-828a-cd8f8b290d6f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e0add202-c16d-4dfc-aa8b-253046f8c52b', primary_key=True, serialize=False),
        ),
    ]
