# Generated by Django 4.0.2 on 2022-06-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f07ba7b9-0e60-4268-87dd-7523ca05f808', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7d429b09-5080-4cb2-b154-eb776ed54ffe', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='e2c15616-5ce1-400a-8902-965abaccd863', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0614541d-b9b5-4f49-bc87-850dfcd83df6', primary_key=True, serialize=False),
        ),
    ]
