# Generated by Django 4.0.2 on 2022-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f13ad965-d748-48bf-938c-6a4ac776d01a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f663f568-42c9-4cbd-8b34-d007f40f6c2e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='486db270-9d69-4fac-a787-eddf14fa5001', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='79544602-fdfd-44e9-9284-e1fa80b303f8', primary_key=True, serialize=False),
        ),
    ]
