# Generated by Django 4.0.1 on 2022-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2427280a-50d1-4a92-a2d4-6ea327d3958b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='54c96618-ef66-446d-a815-a4ee46898a39', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='05892121-12cd-4c03-8a6c-f7a60623d003', primary_key=True, serialize=False),
        ),
    ]
