# Generated by Django 4.0.2 on 2022-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2d3ce947-570e-4330-8a80-4e63e34a3b03', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='115b7c36-5389-4783-8a74-0895cfaa14e0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='930094fc-4383-4686-9cbc-15c9659e9c47', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='bb5b9d93-71a5-41d5-b968-375d06c5982f', primary_key=True, serialize=False),
        ),
    ]
