# Generated by Django 4.0.1 on 2022-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f4f47760-babf-411b-b5d1-f3b2b4f184de', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='b11980a0-1f3d-4541-9852-44520e24b2b3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1567979e-0dd3-4856-8b79-a4cc27ae62d0', primary_key=True, serialize=False),
        ),
    ]
