# Generated by Django 4.0.2 on 2022-06-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='0d183228-dc4f-41e5-93a1-22052ee05b13', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='50c4bcd6-97ae-462d-940a-f95693dfd2fc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='82b28439-b6d8-4ddf-8d0b-09d80e8e26bb', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='4ed06e9d-5f7e-4faf-a2dc-dce6e9293a31', primary_key=True, serialize=False),
        ),
    ]
