<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-15 11:53
=======
# Generated by Django 4.0.2 on 2022-06-17 14:32
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='bd27f396-bb81-42e9-8603-19e04ee78ad6', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='0d183228-dc4f-41e5-93a1-22052ee05b13', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='ef91e4df-5ba0-4d9b-8a8f-288cc687125b', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='50c4bcd6-97ae-462d-940a-f95693dfd2fc', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='2da705c4-3e74-422c-af72-72fb2815fae6', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='82b28439-b6d8-4ddf-8d0b-09d80e8e26bb', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='276dc850-e8c9-427e-93cf-c978da5561ab', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='4ed06e9d-5f7e-4faf-a2dc-dce6e9293a31', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
