# Generated by Django 4.0.2 on 2022-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='fbd50186-0c71-4870-ab2c-3aa71c17f33f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='a4c56a82-98fe-4b48-a092-22a6209dcfb1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='664ea760-63f1-49c2-84c5-af7433777e25', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='45e4c395-d4e4-49bf-854d-30205b348009', primary_key=True, serialize=False),
        ),
    ]
