# Generated by Django 4.0.1 on 2022-02-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='923cd243-f6cd-4972-badd-9dfbb727ceba', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='baa04222-7052-4e89-9c96-b19a4a5fbb68', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='b8304910-a3df-4408-99f7-763f51777eb9', primary_key=True, serialize=False),
        ),
    ]
