<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-16 23:05
=======
# Generated by Django 4.0.4 on 2022-06-17 19:05
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
<<<<<<< HEAD
            field=models.UUIDField(default='ea57aac7-e00d-4e58-947c-ddafc44d39f2', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='20c15ec5-848a-40da-8cf9-c2606b003afd', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
<<<<<<< HEAD
            field=models.UUIDField(default='109969db-7d11-453d-8f18-e5816d68be22', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='5ac092ed-9c0f-4b39-8a36-a6f3af7b41e8', primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
<<<<<<< HEAD
            field=models.UUIDField(default='290ab03f-8766-4dde-82db-229c152a6861', editable=False, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='21307f29-eb37-40c0-89b8-5cdb3ba04757', editable=False, primary_key=True, serialize=False),
>>>>>>> main
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
<<<<<<< HEAD
            field=models.UUIDField(default='7f542dc6-3d64-41e4-9c07-2505e274ffea', primary_key=True, serialize=False),
=======
            field=models.UUIDField(default='c55bcc12-a4b4-458e-8c12-98f613d50d5c', primary_key=True, serialize=False),
>>>>>>> main
        ),
    ]
