# Generated by Django 4.0.4 on 2022-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='20c15ec5-848a-40da-8cf9-c2606b003afd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='5ac092ed-9c0f-4b39-8a36-a6f3af7b41e8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='21307f29-eb37-40c0-89b8-5cdb3ba04757', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c55bcc12-a4b4-458e-8c12-98f613d50d5c', primary_key=True, serialize=False),
        ),
    ]
