# Generated by Django 4.0.1 on 2022-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinput',
            name='customer_csv_uploaded_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2ba8ce15-03e1-473f-a3f1-112379401dc8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7f9d6997-4286-4bd4-a5d0-0339af33f825', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7b9f6b54-8138-479d-9f2c-3da19e00ecb9', primary_key=True, serialize=False),
        ),
    ]
