# Generated by Django 4.0.1 on 2022-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_customerinput_customer_csv_uploaded_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='bc5bd231-6353-479c-9f49-748318bc48bd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='2dd2125a-8804-4e8c-9be3-8d2df3020270', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='fe0f8f32-b416-48c1-b16d-5e6d1a2341ca', primary_key=True, serialize=False),
        ),
    ]
