# Generated by Django 4.0.4 on 2022-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d59e0009-04a9-4685-8e0b-2737def83062', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='16e4ca76-2508-452f-ab65-b3a1f59db24f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='d3c422df-f2f5-46fe-a0a2-ac53338b3ffa', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a05044fc-3cac-474d-8b2f-35d5a6b1f481', primary_key=True, serialize=False),
        ),
    ]
