# Generated by Django 4.0.1 on 2022-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e83ef7c0-8dd2-458d-bb53-21dc286640b7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='147b66c4-cf09-4808-8e6c-edccbc9ba83d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='4b4adc54-78e8-40b8-bc5f-39e8ef52615d', primary_key=True, serialize=False),
        ),
    ]
