# Generated by Django 4.0.4 on 2022-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='eb0f38dc-6228-4a0a-bdd9-67bac8a21a2f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1177c275-ef3d-465b-b3f2-160525f8db29', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='d770d8bb-02c8-4cd7-bac8-7982d4ebdc95', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='73ac0283-4951-48c7-a318-735d6aaf2dcd', primary_key=True, serialize=False),
        ),
    ]
