# Generated by Django 4.0.1 on 2022-02-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b82f71e8-f7e8-4c85-b787-7eebf2e89a8d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='cf457d88-e13c-49f8-bb02-0a46bd5cbe20', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='2eca073b-d266-47b2-af9d-5722902c7efa', primary_key=True, serialize=False),
        ),
    ]
