# Generated by Django 4.0.4 on 2022-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2e49def3-3871-40f2-b602-696d8d1a83ff', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='b3a2ef33-d290-4bb9-b61c-ed068e9cb890', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='f87d8f9f-05fa-4fe1-9c62-1d7df50cfef2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a67884ec-6ab8-48ea-83c5-b3292afd6b07', primary_key=True, serialize=False),
        ),
    ]
