# Generated by Django 4.0.1 on 2022-02-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='ad3c149c-0754-4bf0-834c-41ab6c1a06ec', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='60f093f5-267a-4fd6-9930-79589c35f9b8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='9202fcb5-e931-4848-a79c-a2a51ecbd38c', primary_key=True, serialize=False),
        ),
    ]
