# Generated by Django 4.0.4 on 2022-06-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='ea3d7b92-a52b-404f-a683-6d3dfd0983a1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3562fd12-7119-4670-a9a8-dbfca99d3909', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='8f1f9f56-4f1f-462a-a98e-fdab5b32325e', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='57e49690-57a2-4d35-ba80-e4b825fc65b0', primary_key=True, serialize=False),
        ),
    ]
