# Generated by Django 4.0.2 on 2022-02-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='bb2614c7-9488-4748-b1dd-11665587ed40', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='20d5b560-bf19-4069-9158-a16d39feb3d1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1ebb22e0-4697-43da-813b-3fdd77da07e3', primary_key=True, serialize=False),
        ),
    ]
