# Generated by Django 4.0.4 on 2022-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='ab661737-5171-4cbb-bcb3-b9d94e300edf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='dd87b970-2044-4de0-9e90-c38b17c70b92', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='9cdab091-29b4-4b22-b97b-0a820a4f8c39', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='5d148770-05a0-4e0e-97b0-7728065cf0c3', primary_key=True, serialize=False),
        ),
    ]
