# Generated by Django 4.0.4 on 2022-06-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='52a3c417-ca6d-409b-ab80-d9b33fee9b0d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6253f6eb-f9aa-4e93-8a10-9d9db98b8f8b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='b866e838-9f80-41db-bbda-7b945d67b187', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='fa411341-50a0-410e-ac76-9d4e7d4bd012', primary_key=True, serialize=False),
        ),
    ]
