# Generated by Django 4.0.4 on 2022-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='15279557-9cf3-4c81-a804-97d5878fcbaf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c7c0f267-c3ed-4f47-b237-86ff2182a785', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='806276e1-ec23-498c-8ca7-be0cdf6df61b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1d90591f-6062-488c-a5d7-30edd75f4ef1', primary_key=True, serialize=False),
        ),
    ]
