# Generated by Django 4.0.2 on 2022-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='41ef4d9a-b6ce-492b-9c02-f1ce99293b2c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='566127ae-844c-4a59-98e5-7ac5e4f72b4e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c7303ebf-aff6-4ef0-83bc-fb0a27bf1bbf', primary_key=True, serialize=False),
        ),
    ]
