# Generated by Django 4.0.2 on 2022-02-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d016f4ee-60a5-4b9b-85ca-6cdd2029ebfd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c6af394b-3ecd-4b55-a1be-585ae0d8e172', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e8a7d552-152c-4dec-b0ed-37b2a12a13a4', primary_key=True, serialize=False),
        ),
    ]
