# Generated by Django 4.0.4 on 2022-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f2ba4c7a-a42d-4e4e-94aa-9181dc2e4cb0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1cbc0825-f438-4e06-93e1-4977e5c8224e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='33e6a231-4852-4d97-bb0a-c9cda3405eec', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='3a592694-8b14-4ead-9270-40813b4795a9', primary_key=True, serialize=False),
        ),
    ]
