# Generated by Django 4.0.2 on 2022-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='142aa872-ba9c-4279-85fc-c7157b4aa3ef', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='5af0b15d-4423-4b8e-a828-d106468d018e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e8c51247-4568-468a-82ed-89504d51e75e', primary_key=True, serialize=False),
        ),
    ]
