# Generated by Django 4.0.2 on 2022-02-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a01ea27d-d1e2-4473-9410-a63de06f8329', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ca43dda0-7c9a-4c45-b32e-739f8246312e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='2790376c-6a81-4062-b595-da11cf466ed1', primary_key=True, serialize=False),
        ),
    ]
