# Generated by Django 4.0.6 on 2022-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='53c99c7b-e393-4c11-b8be-41581d67ef49', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='4ee5f2b2-c64d-486b-a623-6bb52ed3c42c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='c2586bd3-0111-4765-abf2-e88e1ff4d2f2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='688e534d-c8e4-4ec2-a812-8039d30261dc', primary_key=True, serialize=False),
        ),
    ]
