# Generated by Django 4.0.2 on 2022-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f05d9baa-3b58-46c3-8cc2-4461735b328a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3868d37b-0dac-4f0c-b27f-0f1fb03f518a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a325bb83-c2e1-4270-b767-e741b91303ee', primary_key=True, serialize=False),
        ),
    ]
