# Generated by Django 4.0.6 on 2022-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6d35133e-1f30-4c18-85ef-22dff89342bb', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='08801f2c-441a-479b-a31d-4d002a70e808', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='2fb4fbc7-039b-4db5-ad38-56a71341e100', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c274f8f5-8bbe-48f3-9f6d-e9be02a2c596', primary_key=True, serialize=False),
        ),
    ]
