# Generated by Django 4.0.6 on 2022-08-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b1d27d93-bb15-41fc-951f-c69f71f581fd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3f75109f-4756-483d-a4f0-5838e5dbd5b4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='c99eb8e4-cbb4-43e8-a45a-84005e6e78d2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8d01fcfd-071e-4c46-b8ec-4f3904d497e0', primary_key=True, serialize=False),
        ),
    ]
