# Generated by Django 4.0.2 on 2022-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='21180f12-6fa7-434f-9574-5db720be1616', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='07c4b43e-6281-4512-acfc-a873c221390d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e539f2be-e7da-4509-953a-46edd16f4243', primary_key=True, serialize=False),
        ),
    ]
