# Generated by Django 4.0.2 on 2022-02-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='ec80a1e3-9c6d-4f20-8ff9-88daf520acbe', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ded53cc4-515f-4adc-8d2d-6674aa2cebff', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='29ab0fc2-5959-4e95-8f24-e6fea709df04', primary_key=True, serialize=False),
        ),
    ]
