# Generated by Django 4.0.2 on 2022-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='3067a0f9-94d9-4478-875c-41287efa8a6d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='05656e58-5698-4c5e-9822-38c16916e10e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='18527523-c9bb-486c-ac1c-4207be590add', primary_key=True, serialize=False),
        ),
    ]
