# Generated by Django 4.0.2 on 2022-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2f06f6da-7002-41d1-83de-e115bf74ba77', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='8ad79e11-4e3f-4b27-ac08-43b6cfce331c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8a96e67d-1a93-42f1-bd1e-53f3d8c64a0e', primary_key=True, serialize=False),
        ),
    ]
