# Generated by Django 4.0.2 on 2022-02-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b8ed4018-7225-4dc9-9e3b-3f88041c84ef', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c240c1a7-2868-4711-84a4-e80c3324a229', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='9487cef1-fda4-4541-b32a-412ea2627312', primary_key=True, serialize=False),
        ),
    ]
