# Generated by Django 4.0.2 on 2022-02-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5bf3667a-c385-4877-9fdf-335b4f6d2bf8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='2df0df14-d451-4bb2-aa6f-3b83337ed273', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='ed0123d3-814d-4445-86db-6d02694877f4', primary_key=True, serialize=False),
        ),
    ]
