# Generated by Django 4.0.2 on 2022-02-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='fdfd186a-b7f5-429e-af16-d787a6f5f30b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='4b48263f-06ba-49bc-9988-fe06c2c17b3a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8692b964-0ef3-482e-9969-d0421e2f520d', primary_key=True, serialize=False),
        ),
    ]
