# Generated by Django 4.0.2 on 2022-02-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='94039507-7a8f-4ef5-8b56-8a67406b2426', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='38be8694-87f3-4376-9823-284baac6925d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='86268ab7-79e5-49af-b80e-bc4f048f7230', primary_key=True, serialize=False),
        ),
    ]
