# Generated by Django 4.0.2 on 2022-02-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='37cedd69-f73f-4d73-8df3-ae0721bf04c6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='78d6f1ec-4079-4246-b583-dd8a5b1e5f0b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='85999ba5-32a7-480e-a266-b13ed38553a4', primary_key=True, serialize=False),
        ),
    ]
