# Generated by Django 4.0.2 on 2022-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d95d786f-7687-4efb-937a-379b7673f302', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='a078db2c-5544-41e9-9166-76ff5f802df4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6989c4cb-38c6-4d83-8071-1e9d31105a3a', primary_key=True, serialize=False),
        ),
    ]
