# Generated by Django 4.0.2 on 2022-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d705e336-c243-4108-b037-054b8d7c00d9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c21c38ce-1b2d-453f-9fea-295204a34678', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='55a4ec7d-0aa9-416e-8aaf-b33cdb337897', primary_key=True, serialize=False),
        ),
    ]
