# Generated by Django 4.0.2 on 2022-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b13c2c51-e249-4830-a927-30c10cd28e09', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ff62f3bc-2d4d-4972-8a9a-173d9f271292', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='dfb4a123-7e0e-4d01-b208-8a845017fbae', primary_key=True, serialize=False),
        ),
    ]
