# Generated by Django 4.0.2 on 2022-02-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e60e9bf0-c023-451d-8521-01cbb762db78', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3690b918-c801-4624-b5c1-6342dd191ff0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='72b7c3cf-d551-4d2b-b0c9-d536d734cf2b', primary_key=True, serialize=False),
        ),
    ]
