# Generated by Django 4.0.2 on 2022-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e91523f3-9166-4207-8afb-19c898ef5c69', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='bbd79c6d-f9ef-45af-8a70-38cf4f60bd57', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='62c73b98-4a04-403e-b219-fdead86b47ff', primary_key=True, serialize=False),
        ),
    ]
