# Generated by Django 4.0.2 on 2022-02-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='8ba16ffc-01b7-44de-8501-8d2d08cfb7a2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='9a6e6a04-9cff-4dac-9a65-88ad4e289fff', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='dd4f8099-0443-44cc-933f-00dea1a80e94', primary_key=True, serialize=False),
        ),
    ]
