# Generated by Django 4.0.2 on 2022-02-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='dec93c9e-025d-4b90-9ce3-f94808986541', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7060318b-ae0d-4cce-930f-cadfbc329991', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e5f84144-2c3e-4442-815c-97efd42dffe0', primary_key=True, serialize=False),
        ),
    ]
