# Generated by Django 4.0.2 on 2022-02-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0074_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='98e9b2a5-dfd3-438f-9fa8-79c5f10dbbed', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6d96e078-fed9-41b7-b2dc-c5d9598ed4df', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='50e1150d-f9fe-42bc-8eeb-3997f3240cdb', primary_key=True, serialize=False),
        ),
    ]
