# Generated by Django 4.0.2 on 2022-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='302432dd-f3f7-404f-af18-6deb57f70853', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='62491c6a-29fd-41da-a020-1ae953e41c51', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e28b0411-7fbb-4cf5-bcf1-fdf6c8cd5850', primary_key=True, serialize=False),
        ),
    ]
