# Generated by Django 4.0.2 on 2022-02-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='da70606b-dce2-4ea9-b825-1d4266f9e35d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='5c3a9af8-e8d5-4c0d-b2cb-6b0beb963aef', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='193994c2-e23c-4258-b26e-1ba11e23c4e3', primary_key=True, serialize=False),
        ),
    ]
