# Generated by Django 4.0.2 on 2022-02-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='03e4d9f8-dc09-495c-ac82-84ad8bc8495d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='36eea9fa-e171-43a7-982a-a78d68d1e4fb', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1fc1cc74-aa18-40e4-abc2-4813d461ac02', primary_key=True, serialize=False),
        ),
    ]
