# Generated by Django 4.0.2 on 2022-02-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0078_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='28d4caec-e375-4380-8e68-0dd468bad7fa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='716ee21c-8318-4824-b97e-660f674a0e9d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='abe7683f-afa5-4d3e-9c36-48c71ea49e24', primary_key=True, serialize=False),
        ),
    ]
