# Generated by Django 4.0.2 on 2022-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0080_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinput',
            name='gridfs_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='751f024e-5ea2-49df-b6f9-99ed7f26caa2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3bdda7ec-d30b-4474-83d7-d88755835814', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='bdea4b52-10f6-4772-ac2b-4d41386c1da8', primary_key=True, serialize=False),
        ),
    ]
