# Generated by Django 4.0.2 on 2022-02-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_customerinput_gridfs_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a2d3f529-2c78-42ce-9ee0-546042d63850', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='59cbc710-f1ea-4b0f-b625-fa61e9f8cb76', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='3fbe21fe-9b5e-44b1-bdae-60f578467b98', primary_key=True, serialize=False),
        ),
    ]
