# Generated by Django 4.0.2 on 2022-02-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2b739c22-56a2-4172-ba8f-3d352f4c0db5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c3954194-7a36-4d65-b76a-35b3d20cc82f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='84fdde47-e2f7-4e37-ae55-31f6955e7664', primary_key=True, serialize=False),
        ),
    ]
