# Generated by Django 4.0.2 on 2022-02-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='31c57278-7030-43c9-b429-4a35d0ef8d9e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1cd476ff-c6ee-41aa-85c2-96720544493e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='931bbde6-2567-43b1-92f8-d067e1c52fe6', primary_key=True, serialize=False),
        ),
    ]
