# Generated by Django 4.0.2 on 2022-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='979279da-a097-4f53-a4f1-5af47af8d59b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='cf7648b9-4aaa-4183-b4c0-6c7eacdee9f6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='765afc8e-e2f9-44df-8422-1d6b8c243f2d', primary_key=True, serialize=False),
        ),
    ]
