# Generated by Django 4.0.2 on 2022-02-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='efc2931d-77f2-42a9-9113-62164b5c3a42', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f7102a64-bdf5-448c-9f66-2fe6b64c05b1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='80e64571-2e62-4c4e-81f5-5d3c4bf2af5b', primary_key=True, serialize=False),
        ),
    ]
