# Generated by Django 4.0.2 on 2022-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0089_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='aa76784b-d883-4660-a719-2675d7a7276a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='93d0884e-c619-464c-8d98-4412b66c6b00', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='684a5e46-0788-453c-9f60-58230e7716e5', primary_key=True, serialize=False),
        ),
    ]
