# Generated by Django 4.0.2 on 2022-02-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='328a3a8c-2fb5-49f8-8ce8-bdcbb507fe0c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='e87b22fe-228c-4c31-935c-612df03fc3ff', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0d7879ea-e04f-48fd-8d48-a65fc5979ea9', primary_key=True, serialize=False),
        ),
    ]
