# Generated by Django 4.0.2 on 2022-02-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6daa2ba6-da56-4050-9ddd-9a8823a0696b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7d1a365b-6aae-4d6e-9162-5ef631afbeb1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='37e62207-3f8a-466f-8b43-a077b44c926d', primary_key=True, serialize=False),
        ),
    ]
