# Generated by Django 4.0.2 on 2022-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0092_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='eaf11fb8-c1fc-48ff-9131-d7cf307348fd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='288d27bd-76e2-4f32-8dd2-3e923fc428e1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='05b507f9-24b9-48ca-91f6-c0511af4e0d6', primary_key=True, serialize=False),
        ),
    ]
