# Generated by Django 4.0.2 on 2022-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='62354d56-1547-448d-ac14-3503a3233bd8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='74eb3854-5610-456a-9480-55f608695afd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='52930595-bba6-4e75-ae68-27edd005b0c8', primary_key=True, serialize=False),
        ),
    ]
