# Generated by Django 4.0.2 on 2022-02-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0094_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='585b84a0-707d-4efd-aeb5-f65e7ad5e462', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='43964e42-309b-4294-afba-ba06f7dc0aa4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='535de677-0878-4c71-9fa5-86da63802b6a', primary_key=True, serialize=False),
        ),
    ]
