# Generated by Django 4.0.2 on 2022-02-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0095_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a56c72c9-12c4-4e71-9483-5ee344f677bb', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f2158280-9fa3-464b-b9c0-8cc96263217b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='589c822e-07ae-4adf-af92-abcc0df577a9', primary_key=True, serialize=False),
        ),
    ]
