# Generated by Django 4.0.2 on 2022-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0096_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='1031658d-cc4b-4efb-a08e-e813ddf39a57', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7f9f7039-09e9-4eea-91ea-f98c67cecd9a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0f4f6f4c-a3a6-4d26-8038-ddc10dd3f79e', primary_key=True, serialize=False),
        ),
    ]
