# Generated by Django 4.0.2 on 2022-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0097_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c1f20d62-1fd3-402b-8787-455e87cc624c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c0b2b92e-1b80-4df4-af78-37705e99e90d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6d3f9149-da1d-43ef-87ad-67b9ba77f178', primary_key=True, serialize=False),
        ),
    ]
