# Generated by Django 4.0.2 on 2022-02-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0098_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6a2cbb90-b1d2-4e95-8fbd-0dde42415b09', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6f44a0e9-c43b-46ff-a5a8-ecb62c34a132', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7a154973-a5ee-4a08-aa5f-0ddeca2963dd', primary_key=True, serialize=False),
        ),
    ]
