# Generated by Django 4.0.2 on 2022-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='1ea277fd-3ad7-4157-adb6-c9e3ddbdb3ac', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ac90bc42-0fda-4520-9127-ea035246e28d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7d5df88a-6746-4966-8d3c-26b28e00bf38', primary_key=True, serialize=False),
        ),
    ]
