# Generated by Django 4.0.2 on 2022-02-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0100_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='87a67747-d745-469f-8b72-7ba3fcf1a34f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f4449438-47d4-444d-be0c-a1194cb225e2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8e87b632-3485-467a-a3a4-d1e9875fac29', primary_key=True, serialize=False),
        ),
    ]
