# Generated by Django 4.0.2 on 2022-02-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0102_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='f0cf3718-b05a-41fc-ab0b-face40b671b2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7d19997d-d71e-4bd4-a23b-98a4349f9b3e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='db0f14b7-c9d2-4d7a-8613-48723237af6e', primary_key=True, serialize=False),
        ),
    ]
