# Generated by Django 4.0.2 on 2022-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0103_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='7fece345-c077-4d8d-9309-3c6326b10bee', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='02758940-b7b4-4409-8709-2013f29aabf1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='4e425aa1-fa72-4463-9c87-cad372b9edf4', primary_key=True, serialize=False),
        ),
    ]
