# Generated by Django 4.0.2 on 2022-02-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0104_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='390b4585-53c9-44de-837e-028d2cbb1e1c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='17b63efe-56f5-4e2f-9e69-ba017af6b005', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='45cf396a-3794-4a32-9005-f3664b02911c', primary_key=True, serialize=False),
        ),
    ]
