# Generated by Django 4.0.2 on 2022-02-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0105_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='8d08b37e-4792-4f67-83da-140f63d16a60', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='15f60036-9ad0-4d17-9032-09680d145d9c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8142d4b7-84c0-4d6f-ac73-0218cd219656', primary_key=True, serialize=False),
        ),
    ]
