# Generated by Django 4.0.2 on 2022-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='aeaf603f-9c0a-4f46-9f9c-55c5dd29fee8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c9e6992a-cac4-4120-83b1-61d9aed4b168', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='ce660765-cd1c-47e3-8f1d-3df79d912c57', primary_key=True, serialize=False),
        ),
    ]
