# Generated by Django 4.0.2 on 2022-02-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0107_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b23bab10-96e1-49cb-9ec2-f224d47eae35', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='bd3eda35-d933-4c7d-8ffe-1ac129279d33', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='fe6081d3-2a77-45bc-9fd6-cf65c54cb53c', primary_key=True, serialize=False),
        ),
    ]
