# Generated by Django 4.0.2 on 2022-02-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0108_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='49071f8b-d8ba-4bd0-8301-ff555aeac417', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c01bc0e5-9274-484f-9fe5-1a0cdf70febf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d0b9753b-a5ea-4e4f-a3d4-d7a345aebad2', primary_key=True, serialize=False),
        ),
    ]
