# Generated by Django 4.0.2 on 2022-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0111_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b58ea6b0-cee7-46b0-a14f-b79a0800d49a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d1bdb6f6-d83c-4147-806a-c413d3dd0f6d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f092bd21-7c7d-44a4-98c0-ab05c8e4143b', primary_key=True, serialize=False),
        ),
    ]
