# Generated by Django 4.0.2 on 2022-02-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0112_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='8a5afc76-bc15-47f5-bace-b87a723eacb5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c7582abd-e2dd-417a-906c-e41d83688b76', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6a2d6417-e0fc-4b16-9af4-c99b4c5b864e', primary_key=True, serialize=False),
        ),
    ]
