# Generated by Django 4.0.2 on 2022-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a8ca44eb-2cbf-424d-957c-13f33435c2ee', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='9d1ce1bf-1b6d-4a0c-b00d-62ce76587ec1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6e829b87-f0f7-47f3-8505-155fe26f3d70', primary_key=True, serialize=False),
        ),
    ]
