# Generated by Django 4.0.2 on 2022-02-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0115_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='66c47568-dd78-4c16-b009-63908c52293f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='14741aa1-3771-4242-a1a5-c1c46b92b171', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='94722054-040f-4282-a4cb-922daa264242', primary_key=True, serialize=False),
        ),
    ]
