# Generated by Django 4.0.2 on 2022-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6e748e49-da03-472d-8076-904673838332', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d9fde741-11bb-4dd2-a621-e437ecc36f4e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e3bd8de6-b6df-4fa8-9a1a-e386813ac7d8', primary_key=True, serialize=False),
        ),
    ]
