# Generated by Django 4.0.2 on 2022-02-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0117_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='753568b6-3fe2-4d14-815f-aaa656789bda', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='0d6f5731-edc2-47bb-8cdf-de6d23a5ace0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c7a0c94e-31b6-4297-a79c-8fc1f98f59af', primary_key=True, serialize=False),
        ),
    ]
