# Generated by Django 4.0.2 on 2022-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0118_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='58e4d577-5904-4ce2-9516-2403fe973724', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='2f62f7bc-b4aa-4a6c-bbde-3791301cdda8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c2f2ab80-9804-40e1-8212-f0371c9ec686', primary_key=True, serialize=False),
        ),
    ]
