# Generated by Django 4.0.2 on 2022-02-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0119_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='441444bd-feb9-4826-9857-29b4fb724806', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d79f201e-5098-4e4a-807f-3f8c008e1762', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='ca81ed58-5cb4-4ad6-95e6-22b16c7d7876', primary_key=True, serialize=False),
        ),
    ]
