# Generated by Django 4.0.2 on 2022-02-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0121_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d83da430-265c-4839-a950-b476c4b156ed', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6793e316-db85-4a99-86d9-011a91ed3416', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='9bf28cdd-714a-48dd-9ff1-bd1b138fcda9', primary_key=True, serialize=False),
        ),
    ]
