# Generated by Django 4.0.2 on 2022-02-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0122_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='cf523a34-cfcf-4aa0-8aec-f3586e39844a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='bde82e79-9bba-46d3-a9f6-82cea4d9fc00', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1ef2505a-ae45-4698-9cc6-3765087a15d8', primary_key=True, serialize=False),
        ),
    ]
