# Generated by Django 4.0.2 on 2022-02-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0123_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='943ac829-8d40-48f3-8ace-300473b08b1f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='4866927b-4a1b-4a99-964c-d1557c0b96f2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='4190a0ef-16dc-4eb9-b687-3d51265de868', primary_key=True, serialize=False),
        ),
    ]
