# Generated by Django 4.0.2 on 2022-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0124_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='92094817-ae0f-4f9f-ba7f-6afd9fabd5b6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='639cb855-e5f9-4f50-89c1-4c03fe8b4c7c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c4c5abb9-e22f-4ac1-8d7d-4c3f5ecf0237', primary_key=True, serialize=False),
        ),
    ]
