# Generated by Django 4.0.2 on 2022-02-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0125_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6b8eeea1-8d3d-4ce0-a027-cf95ef46c094', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c7d986bc-cce4-470a-b92e-0810a3b9387c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='105e9ba8-db4e-4ce7-9c29-4ba630ac688c', primary_key=True, serialize=False),
        ),
    ]
