# Generated by Django 4.0.2 on 2022-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0126_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='578127ad-612c-48ce-9a50-a9d53b44fe4e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='bb309fc6-07d1-4775-9043-52e0d67d53fd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='24c69013-977f-4ac4-98b7-46978f686899', primary_key=True, serialize=False),
        ),
    ]
