# Generated by Django 4.0.2 on 2022-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0127_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='111591f2-ea39-420a-8794-0d922a055d81', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ad908cb2-cd13-494e-a52e-07d26437a3b7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='fc57f500-4d19-4c9c-a8a4-b0520abe0f81', primary_key=True, serialize=False),
        ),
    ]
