# Generated by Django 4.0.2 on 2022-02-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0128_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='66fbb7c8-e4a3-4dbc-9dfa-247b5c4d06b6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='16f8f332-91e9-4aa0-85be-8c6e21324d96', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0a6b25ab-613b-4b10-b2a0-66965dd67435', primary_key=True, serialize=False),
        ),
    ]
