# Generated by Django 4.0.2 on 2022-02-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0129_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='d56dc85b-e52e-4371-92ed-0570c6aff9b9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6fb9cfca-ed63-44ae-b32c-cee302cbdfe8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f8cb682f-ccac-4ebb-8eb6-4e7f90a24e82', primary_key=True, serialize=False),
        ),
    ]
