# Generated by Django 4.0.2 on 2022-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0130_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='7f63fb36-a69a-4492-b0b0-327794fc3a39', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='a2787385-0123-47af-b28b-866e7b8c794f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='11a6f477-fbe8-4b35-882e-05c8483f1912', primary_key=True, serialize=False),
        ),
    ]
