# Generated by Django 4.0.2 on 2022-02-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0131_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e2a9940c-2958-4597-9eb4-af32fe18951a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='748cb28c-8adc-43f2-afb5-d3fd4418930e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6944514d-80a2-4ad1-84b5-8b2cbd2a5bae', primary_key=True, serialize=False),
        ),
    ]
