# Generated by Django 4.0.2 on 2022-02-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0134_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2317a901-840b-4eb9-bf0d-f1a834cbd1ba', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3aefb85a-a80c-446c-9702-e009b076bdc7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='ac389f82-2c4f-4517-9baf-736355a49067', primary_key=True, serialize=False),
        ),
    ]
