# Generated by Django 4.0.2 on 2022-02-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0136_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a6ad1606-71ee-4e85-8874-6b297913ca9a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='401ae83d-84fb-49a8-b1c1-ad0bff455b33', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a4cc644f-4e39-4e6e-ac81-d2de341ebaf8', primary_key=True, serialize=False),
        ),
    ]
