# Generated by Django 4.0.2 on 2022-02-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0137_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='1678e32e-2119-4a2b-aa90-d2ddc40a4059', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ad0dc090-635b-40c8-8c47-a2002045162d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='347475a2-cc7a-476a-9f6c-12803d685f21', primary_key=True, serialize=False),
        ),
    ]
