# Generated by Django 4.0.2 on 2022-02-26 03:38

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0138_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='56556d4b-ef5b-4bad-8c14-a50e0fd134fd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d45f0219-0264-4e57-bcd8-e35e93c8ca08', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='08b9b7f1-3be0-4159-af81-0164797711b0', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('retail_store_code', models.UUIDField(primary_key=True, serialize=False)),
                ('retail_store_name', models.CharField(max_length=1000)),
                ('retail_store_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('retail_store_city', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
