# Generated by Django 4.0.2 on 2022-02-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0139_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='6fc88d6b-dc36-4d01-9d42-b91ae618c496', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='2060e8ee-c521-4438-8cbc-12e580ac95a1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='92426154-905d-4294-9b96-917276990cbc', primary_key=True, serialize=False),
        ),
    ]
