# Generated by Django 4.0.2 on 2022-02-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0140_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='7af2f4ff-7e99-43d0-9802-c66f0baa7f57', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='40e20db6-3c9b-469f-9450-50aa4a4c4600', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f72cce27-d548-4ad2-a859-c125fac67faf', primary_key=True, serialize=False),
        ),
    ]
