# Generated by Django 4.0.2 on 2022-02-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0141_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='dcc5442a-db57-43bc-8f84-4bc89bbffd8f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='16697a37-96bd-4812-a559-3c8381c55f46', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d7b440e9-a575-4d1f-b25e-40d99f6ed91c', primary_key=True, serialize=False),
        ),
    ]
