# Generated by Django 4.0.2 on 2022-02-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0142_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b479c423-8e7a-47ac-87a9-05bb1995f288', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='0c66e8d4-e613-40ea-94e0-50ee375ff73f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='b7f59214-fc53-4c63-8ed1-ace58ad20531', primary_key=True, serialize=False),
        ),
    ]
