# Generated by Django 4.0.2 on 2022-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0143_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='66867042-3585-4e64-b9fe-ef552c64a1dd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ec38a387-29a2-4bc4-bf8d-7d06edb87b2c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='94faf845-ae6e-4b95-a8f8-0d5eca075fee', primary_key=True, serialize=False),
        ),
    ]
