# Generated by Django 4.0.2 on 2022-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0144_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5864941b-1c2a-4311-ab81-2a291f5b75a2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='4c40ed43-490d-416f-8eda-ee90f01f9bae', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='f4f3d784-5a58-4a5a-98eb-2457b3d5abc8', primary_key=True, serialize=False),
        ),
    ]
