# Generated by Django 4.0.2 on 2022-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0145_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4131e613-c1ad-4696-9d8f-682719e40f96', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='67981acd-a8fa-4449-9475-f4141b381674', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='fc5a12a9-9d24-41ba-b867-8f640b37f593', primary_key=True, serialize=False),
        ),
    ]
