# Generated by Django 4.0.2 on 2022-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0146_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='715ce4fb-4e62-4865-8feb-fe101c120de6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d6dbd3dd-374b-488d-9243-8332a973166f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='11cea95a-fca2-4bf6-9f42-f0ef0696440a', primary_key=True, serialize=False),
        ),
    ]
