# Generated by Django 4.0.2 on 2022-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0147_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4ee68faa-72e1-4812-8dcd-eff0e3b03617', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='eb08202c-c387-4573-9892-a3184dde6fa9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0da1b581-eee1-451a-9979-c061a9a1d331', primary_key=True, serialize=False),
        ),
    ]
