# Generated by Django 4.0.2 on 2022-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0149_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='2de21434-c118-40b2-91d8-c0923e44ca8c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d2c290d5-049e-4a1f-823c-1357e08f18c5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6dab21da-3e78-41e0-aab9-297586f77ebc', primary_key=True, serialize=False),
        ),
    ]
