# Generated by Django 4.0.2 on 2022-02-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0150_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='74cbb9c2-6ea5-4e3b-a14c-3ce59631f223', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1cfb7169-270d-4f88-a60b-b62ee514da93', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='9b6e5f05-bd63-4113-8dab-41f899374039', primary_key=True, serialize=False),
        ),
    ]
