# Generated by Django 4.0.2 on 2022-02-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0151_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e2021098-b26e-4405-bcd8-666b378a9a27', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='bea07040-e444-4ca1-a9f9-13acacc69ba0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='b0393c03-74cf-4ef7-b707-4a38a81322f7', primary_key=True, serialize=False),
        ),
    ]
