# Generated by Django 4.0.2 on 2022-02-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0152_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='07388afa-7458-40f0-9873-2d553cbdfeb7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='10c0a7a7-a4ed-476f-9530-34499c12c900', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='b8ec19cf-c17c-4ba1-a2a2-11e35c1e072f', primary_key=True, serialize=False),
        ),
    ]
