# Generated by Django 4.0.2 on 2022-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0154_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5b747429-c852-4665-8632-f49ded0a04f9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='08ac0cf7-ef0e-4dc7-b419-4672e4dbbe31', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c5084412-b888-46cb-88c8-2ac968feafcd', primary_key=True, serialize=False),
        ),
    ]
