# Generated by Django 4.0.2 on 2022-02-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0155_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='5fb921bc-844c-4e38-909a-89eeb9db9d7a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='66d79618-0f2b-4ba2-8aa1-43fe1ce2116b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='39fad031-47c7-41ca-aebc-1e86872e6945', primary_key=True, serialize=False),
        ),
    ]
