# Generated by Django 4.0.2 on 2022-02-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0156_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b1ec8628-a9c1-4d2f-ba08-8c9fd91d5f99', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='4556dc2a-f9e3-4e98-8e3f-ed0ad5832509', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='bec7d7d6-1a83-4a7a-87eb-909aa67494c5', primary_key=True, serialize=False),
        ),
    ]
