# Generated by Django 4.0.2 on 2022-02-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0160_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='a967b00c-b73a-48be-8a3e-60b7420539c9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='cb342db5-cdd7-416f-b029-481145b1723f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='5150da11-4be8-46e3-a712-2e522dbebe7f', primary_key=True, serialize=False),
        ),
    ]
