# Generated by Django 4.0.2 on 2022-02-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0162_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='fe6bfb94-bfb6-45dc-aa18-4f682fa0a222', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='e2883d74-c116-4b74-a801-435f6305c031', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='dff5ba25-a97e-40f3-8a41-1911c5d21b2f', primary_key=True, serialize=False),
        ),
    ]
