# Generated by Django 4.0.2 on 2022-02-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0163_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='cedf66de-4257-4989-bbac-9b718803938c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='58fde81a-753c-482c-8ed9-e8fce449b6a1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='4219ceb1-122a-4225-b882-6598021179fb', primary_key=True, serialize=False),
        ),
    ]
