# Generated by Django 4.0.2 on 2022-02-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0165_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='7f685da8-b77d-439e-8aeb-f386873e1730', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='1574466a-3748-4c12-b7f2-363119250f7e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='ab90931f-98ee-4a8e-a691-0e2fd605d60f', primary_key=True, serialize=False),
        ),
    ]
