# Generated by Django 4.0.2 on 2022-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0166_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e1650b36-7bf2-488e-af04-785069f19d54', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='f1354926-abe7-42ac-aa0d-4e2bf9e629cd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='b6144fa3-5acb-4473-85bf-0bed13d6872d', primary_key=True, serialize=False),
        ),
    ]
