# Generated by Django 4.0.2 on 2022-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0167_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='863dd4f9-a65e-4959-9868-8c6cb17da71c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c5258b77-3a14-4d96-8ce8-19954a643fab', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='5077b599-dbe7-4ea9-8e54-2b4d24261c92', primary_key=True, serialize=False),
        ),
    ]
