# Generated by Django 4.0.2 on 2022-02-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0168_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUserGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
                ('customer_user_group_code', models.UUIDField(default='9e880f5a-8fa3-4463-abbb-4811734c820f', primary_key=True, serialize=False)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('user_access_level', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(blank=True, through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4fc14111-e04a-4ba4-a5d7-5ccfb4a5e5de', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='490e195b-0c1b-4df0-a6ce-47c038813f66', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='a06e989d-44ea-4acb-8ad1-eabd35d09ee1', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customerusergroup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer'),
        ),
        migrations.AddField(
            model_name='customerusergroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
    ]
