# Generated by Django 4.0.2 on 2022-02-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0169_customerusergroup_customer_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='cec252dd-1a8f-4216-9050-7a52250ca3c0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='743ba789-1217-4f0f-9c71-ce5015185136', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='6e0c3d53-e7fd-4c2a-8a30-b91d479f9e61', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='59fed988-47a8-4d85-902d-2c2beb9df23a', primary_key=True, serialize=False),
        ),
    ]
