# Generated by Django 4.0.2 on 2022-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0170_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='97547638-e592-4d32-8712-e140d5b81e5f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c1a887db-8ff7-4db9-8a28-bac88f32b87b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='0a4b569f-ccc0-4b45-ae6f-542bda6b45b0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='94433390-4fcc-42c7-9616-2d9f4449bfa5', primary_key=True, serialize=False),
        ),
    ]
