# Generated by Django 4.0.2 on 2022-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0171_remove_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b1be8bd1-dd51-48f2-aa01-9580cfd06f9f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='a8b00a1c-d753-4520-b1db-c298b521e0e0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='064f4240-076d-43a6-94cb-f39ded350556', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='d87726b8-25a8-4eff-8f21-f3c2fdc505d2', primary_key=True, serialize=False),
        ),
    ]
