# Generated by Django 4.0.2 on 2022-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0175_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='54943697-553e-42d1-8406-92e850f01f2b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='3b2c60dd-b397-41c3-adf0-68df1dfc61dd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='7da27e64-2da0-42b5-b335-cd6db1066a44', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c67cbc66-d4ae-4d74-969a-7ee918853405', primary_key=True, serialize=False),
        ),
    ]
