# Generated by Django 4.0.2 on 2022-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0176_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='99c2bb1b-ad5f-4927-a514-0c9626fd7507', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='ef46b32e-db40-48b0-a5c3-bc0195d531fa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='c3b35ec4-3357-485a-9367-7079d740be16', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='5043c9a7-962e-4343-96bc-2c9ec62ef1f4', primary_key=True, serialize=False),
        ),
    ]
