# Generated by Django 4.0.2 on 2022-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0177_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c1f04cc7-926f-4099-985d-4b7b409a61a6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='06a03fff-4a2b-46c4-852a-5561959f8186', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='b5380d56-89d4-40cf-b3f4-1a0ab1a5c5c0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='3672d181-ca65-466f-be36-a70a2eb4410b', primary_key=True, serialize=False),
        ),
    ]
