# Generated by Django 4.0.2 on 2022-02-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0178_alter_customer_customer_code_alter_customer_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='27c11089-33d6-4393-9f14-387c899d28b8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='507002b5-2f54-4d7a-87e0-f3d596baaa02', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='aabb18b7-aa98-4eaf-9186-394520a547f3', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='1bd2be58-3266-4071-a39d-b02a56a90998', primary_key=True, serialize=False),
        ),
    ]
