# Generated by Django 4.0.2 on 2022-02-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0179_remove_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='530282fd-690f-4c96-96f7-f4efb21e7da7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='46ea4f16-21a3-4eac-a293-bb32f887fd1c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='026caa1f-b9ed-4289-a825-4493acc30d37', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='6dff1598-abab-4652-b23c-77f4550275c5', primary_key=True, serialize=False),
        ),
    ]
