# Generated by Django 4.0.2 on 2022-02-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0182_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='8bf0eecf-1585-4c61-8246-7a5721924d59', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d7426e34-6225-4156-8b95-695c236b2da8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='738e3745-2821-4ff4-8c4e-26cc0a1788c7', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8663da50-44b6-42da-843c-764021640ab4', primary_key=True, serialize=False),
        ),
    ]
