# Generated by Django 4.0.2 on 2022-02-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0184_remove_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b0dc865e-b3e2-4e9a-bcae-ecb343494862', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='72d0c702-5d35-4326-8810-8c0365c33f69', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='aed1185e-538b-431a-b094-94dddea9e12d', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='696a58c5-4aa4-4585-8bc4-41931d64e62b', primary_key=True, serialize=False),
        ),
    ]
