# Generated by Django 4.0.2 on 2022-03-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0186_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='9a2ab354-0c4e-4119-9d29-2db54ebdd4e6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='01de331f-6df8-4e4f-bbe4-8e43684ccbe4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='fb4aa6bd-9cc1-4a27-a1cc-ab9d54825d08', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='797d486e-c1d3-4241-b320-eea8c353f6e6', primary_key=True, serialize=False),
        ),
    ]
