# Generated by Django 4.0.2 on 2022-03-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0187_remove_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b2c48f83-b6ad-4309-aa02-45e204b6640a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='6f0b64c0-60ef-418e-834d-a019ec144286', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='2e8d3699-ae5e-4d8d-b14b-fc6b13badf9f', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0ee18dca-e7ed-4a4c-a68d-bcbe376376e3', primary_key=True, serialize=False),
        ),
    ]
