# Generated by Django 4.0.2 on 2022-03-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0188_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='474c06fe-f6e4-4282-a8ee-86376b5bb011', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='c382dab4-217a-43d5-b4c7-75798f6dc51a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='a01a458c-8e86-4a07-b26b-4ef1d139922b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='9f093bbe-62d3-4353-b0a5-b30062dbe1d5', primary_key=True, serialize=False),
        ),
    ]
