# Generated by Django 4.0.2 on 2022-03-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0189_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4fe348eb-73da-4080-9693-6816e0cb9c37', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='b15c3536-3b36-4e17-a810-fa328e9b6952', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='edb5fa45-a7db-4218-9975-0cf70042b138', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='354828d1-058b-4670-9856-46aeddf2d376', primary_key=True, serialize=False),
        ),
    ]
