# Generated by Django 4.0.2 on 2022-03-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0191_remove_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='c4bf00f1-6e36-4b93-89c8-0f7e8bd7b132', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='a9f8b407-5599-4bfe-94d9-fb2dc9c26e33', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='872c44bf-f28a-4d0f-96c9-743a0267a0f4', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='e0020847-7fae-4f28-9261-941714ad6f37', primary_key=True, serialize=False),
        ),
    ]
