# Generated by Django 4.0.2 on 2022-03-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0192_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='b4e2d77c-b2a8-42f2-bad2-e26d7d4780f5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='94763172-f7d5-4414-95b1-77cb1b42aa86', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='a9eb8a7e-f88a-4460-8d43-eef21d20ca30', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c67d3419-b6ea-435e-9669-692f5c7eca3b', primary_key=True, serialize=False),
        ),
    ]
