# Generated by Django 4.0.2 on 2022-03-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0193_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='038456a1-e51a-46df-b51e-2c86c08eeb18', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='2fe954db-2614-47f5-9279-bf00bfb836cf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='d3aabf00-43a4-47bc-805a-64786e72bec9', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='c6a962eb-0516-4464-9df6-6cb8a77e543a', primary_key=True, serialize=False),
        ),
    ]
