# Generated by Django 4.0.2 on 2022-03-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0195_remove_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='186639ff-1623-4195-aa81-f2d01d397372', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='0302af8a-36d7-4dba-aed9-58646bae68c9', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='70ef2ff7-b137-4c7c-9f56-1b2dcf8b7790', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8e5ed49a-76bf-426e-a515-a4fc371647ae', primary_key=True, serialize=False),
        ),
    ]
