# Generated by Django 4.0.2 on 2022-03-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0196_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='9588d896-526d-43b7-95c1-29f9116adf5f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='dcb00d40-306c-40dd-b2cc-e0966b78731c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='bd40e4ed-79b1-4b97-bc5d-7384aa3a92b5', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='395fdd5f-e425-41b7-8b2b-30eab08c024c', primary_key=True, serialize=False),
        ),
    ]
