# Generated by Django 4.0.2 on 2022-03-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0197_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='9f11d942-7170-4e6d-a6f1-baa71d7d91c1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='fa43481c-db3f-49f7-a773-b5d2bb0a359d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='8fd64aab-2355-417d-93a4-f05a4b8e80fb', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7c7aa09f-9a11-40cb-b11e-ab60b07ca5ef', primary_key=True, serialize=False),
        ),
    ]
