# Generated by Django 4.0.2 on 2022-03-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0198_remove_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='data.CustomerUserGroup', to='data.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='e0b7411d-8946-478f-83a4-cb52fe3f1f84', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='fb47d9e1-edc5-4d96-bb57-1cffa8c53c0e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='5417e073-aa7e-4a09-83ec-22e56a615f76', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='8af05a40-aea8-40e5-bcdc-3b91ad18d94a', primary_key=True, serialize=False),
        ),
    ]
