# Generated by Django 4.0.2 on 2022-03-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0199_customer_users_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='50d1d2d2-6616-4bd5-8e9e-9fb8b96e27b5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='d6353809-f8e5-4f7d-b067-a75f3a2b559d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='b47666f9-3acc-4236-b697-fac3b2cc7e34', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='bb8c6f25-c1fd-4935-9d35-52f9961bf2fd', primary_key=True, serialize=False),
        ),
    ]
