# Generated by Django 4.0.2 on 2022-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0203_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='8e8c605b-72e5-409f-b8ca-a0dab728463f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='17b6d586-72ae-4709-a1dd-d4b4a1c9adc5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='97d10816-65fc-46e5-b04a-319d075200f6', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='81d7aea1-a8d9-4aee-9213-485761878e53', primary_key=True, serialize=False),
        ),
    ]
