# Generated by Django 4.0.2 on 2022-03-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0204_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='80845e58-6609-4087-8fa1-56cf31662c28', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='7f5fe72b-eefa-42b6-8fd6-3b8c1a527c8e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='012fc7c7-d7be-4db8-83be-840b9902e77c', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='5e2b2eac-c591-44d3-9691-aa497b81885d', primary_key=True, serialize=False),
        ),
    ]
