# Generated by Django 4.0.2 on 2022-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0205_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='4f8303fd-b7b5-48fc-b978-dddc69f2ef2b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='48ee9517-67b4-4958-bbeb-dcc7831579a1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='c0f9c1ff-0f41-4b84-9992-aad15eb3e5c1', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='df1c5e94-2b90-4707-bcbb-c6e106360651', primary_key=True, serialize=False),
        ),
    ]
