# Generated by Django 4.0.2 on 2022-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0209_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.UUIDField(default='42dc1c9a-b180-4fe6-8f45-c7eb9d1a61ae', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerinput',
            name='customer_input_code',
            field=models.UUIDField(default='391bc4a5-d2a5-4886-b1bf-7cc1778408aa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerusergroup',
            name='customer_user_group_code',
            field=models.UUIDField(default='fa16cbaa-bb8c-4e88-bb41-aca1364d3b01', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='66368c92-2439-43c2-9c88-022d7c575d85', primary_key=True, serialize=False),
        ),
    ]
